### PR TITLE
Add new function get_api_collection

### PR DESCRIPTION
**Pull request by tonisefton**
This change is [Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/9)

### CODE REVIEW

**Review by i-mann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/9)* status: all files reviewed, 1 unresolved discussion (waiting on @mterring and @tonisefton)

___
*[`src/objects.rs` line 55 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/9#-NQY8I5T6baP-6kSIodp:-NQY8I5T6baP-6kSIodq:b-tr96v0) ([raw file](https://github.com/WORK180/hubspot-api/blob/92c0ac73af5c3e49a5764c007bd5f20c1026ca96/src/objects.rs#L55)):*
> ```XML
>     }
> 
>     pub fn get_api_collection(&self, object_type: ObjectType) -> &ApiCollection<ObjectType> {
> ```

maybe just `get_collection`? Is it obvious that these are collections for the hubspot API objects?

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/9)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @i-mann and @mterring)

___
*[`src/objects.rs` line 55 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/9#-NQY8I5T6baP-6kSIodp:-NQYia8V-tbSDQ2Kqil4:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/92c0ac73af5c3e49a5764c007bd5f20c1026ca96/src/objects.rs#L55)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

maybe just `get_collection`? Is it obvious that these are collections for the hubspot API objects?
</blockquote></details>

Done.

**Review by i-mann — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mterring)

**Review by i-mann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mterring)

**Pull request merged**
