### PR TITLE
ENG-1109 Add read owner by ID

### PR DESCRIPTION
**Pull request by tonisefton**
This change is [Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)

### CODE REVIEW

**Review by i-mann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: all files reviewed, 1 unresolved discussion (waiting on @tonisefton)

___
*[`src/owners.rs` line 73 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/8#-NQSGhaDD_TZlxoG-W8n:-NQSGhaDD_TZlxoG-W8o:bste3lx) ([raw file](https://github.com/WORK180/hubspot-api/blob/eeaeb116db252848506abb135268d8fa562eaf95/src/owners.rs#L73)):*
> ```XML
> 
>     /// Returns the owner for the given ID.
>     pub async fn read(&self, id: &str, archived: bool) -> HubspotResult<Owner> {
> ```

is there a default on the API that we can recommend/use in the function signature?

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: all files reviewed, 1 unresolved discussion (waiting on @i-mann)

___
*[`src/owners.rs` line 73 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/8#-NQSGhaDD_TZlxoG-W8n:-NQSzBp8A5MIZCM8Uoum:bv3suh) ([raw file](https://github.com/WORK180/hubspot-api/blob/eeaeb116db252848506abb135268d8fa562eaf95/src/owners.rs#L73)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

is there a default on the API that we can recommend/use in the function signature?
</blockquote></details>

Like what we did for entitlements `active_only: Option<bool>.`... a`ctive_only.unwrap_or(false)` ?

**Review by i-mann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: all files reviewed, 1 unresolved discussion (waiting on @tonisefton)

___
*[`src/owners.rs` line 73 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/8#-NQSGhaDD_TZlxoG-W8n:-NQT-Mjl9wzXlzm-45Qg:bc4c42d) ([raw file](https://github.com/WORK180/hubspot-api/blob/eeaeb116db252848506abb135268d8fa562eaf95/src/owners.rs#L73)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

Like what we did for entitlements `active_only: Option<bool>.`... a`ctive_only.unwrap_or(false)` ?
</blockquote></details>

Yeah. I think retrieving active values is the default action - getting archived results is a special case

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @i-mann)

___
*[`src/owners.rs` line 73 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/8#-NQSGhaDD_TZlxoG-W8n:-NQTfC18-K9a7DSU6lMF:bb6un1j) ([raw file](https://github.com/WORK180/hubspot-api/blob/eeaeb116db252848506abb135268d8fa562eaf95/src/owners.rs#L73)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

Like what we did for entitlements `active_only: Option<bool>.`... a`ctive_only.unwrap_or(false)` ?
</blockquote></details>

Done

**Review by i-mann — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tonisefton)

**Review by i-mann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tonisefton)

**Pull request merged**
