### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by tonisefton**
This change is [Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/2)

### CODE REVIEW

**Review by i-mann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tonisefton)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/2#-NN4iudo7XodeMp-WgYj:-NN4iudo7XodeMp-WgYk:b6y7ach) ([raw file](https://github.com/WORK180/hubspot-api/blob/3c1375cf428aa8b0935e22c299642b8e8589f1cc/README.md#L74)):*
> ```Markdown
> 
> ## Suggestions and Issues
> In the meantime please open an issue on github, and we will prioritize accordingly.
> ```

Did you mean to include the first half of the former sentence? i.e.
```
At this stage we are not configured to accept contributions. In the meantime please open an issue on GitHub, and we will prioritize accordingly.
```

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @i-mann)

___
*[`README.md` line 74 at r1](https://reviewable.io/reviews/WORK180/hubspot-api/2#-NN4iudo7XodeMp-WgYj:-NN5FswMC0C-K1peBn2Y:b-18262b) ([raw file](https://github.com/WORK180/hubspot-api/blob/3c1375cf428aa8b0935e22c299642b8e8589f1cc/README.md#L74)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Did you mean to include the first half of the former sentence? i.e.
```
At this stage we are not configured to accept contributions. In the meantime please open an issue on GitHub, and we will prioritize accordingly.
```
</blockquote></details>

No, no I did not, have updated

**Review by i-mann — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tonisefton)

**Review by i-mann — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tonisefton)

**Pull request merged**
