### PR TITLE
REFACTOR : Experiment with traits

### PR DESCRIPTION
**Pull request by tonisefton**
Goes with https://github.com/WORK180/provisioningservice/pull/31

- - -
This change is [Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)

### CODE REVIEW

**Review by i-mann — COMMENTED** [review]
Were the model name updates going to go in this change?

> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4#-:-NPQ531J5FPE3OM2MIsA:bqcn62s)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @mterring and @robmarto)

**Review by tonisefton — COMMENTED** [review]
I started down that road, but have moved those changes into another branch (provisioningservice branch)so that we can better focus on them separately to the hubspot-api refactor

> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4#-:-NPQktSl5yOq6EdZZR-w:bndbb1g)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @mterring and @robmarto)

**Review by robmarto — COMMENTED** [review]
I assume these changes are breaking? If we are planning on doing more refactor that is breaking, we probably shouldn't release this version until they have all been made and then call it 1.0. Or at least come up with a plan since it's a public crate after all.

> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4#-:-NPQoex-E07VwR2BxQ6Z:b66ne1w)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @mterring)

**Review by robmarto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: 0 of 29 files reviewed, 5 unresolved discussions (waiting on @mterring and @tonisefton)

___
*[`src/builder.rs` line 36 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQs9Si1aeLLSW-5vsK:-NPQs9Si1aeLLSW-5vsL:b-pi7ecf) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/builder.rs#L36)):*
> ```XML
>             .token
>             .as_ref()
>             .ok_or(HubspotBuilderError::MissingToken)?;
> ```

Why are these Optional if we are returning an error when they are None?
___
*[`src/builder.rs` line 77 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQsjuP-MDJTUTKQK9r:-NPQsjuP-MDJTUTKQK9s:b-7s8ie1) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/builder.rs#L77)):*
> ```XML
> 
> /// The error type which is returned from building a [Hubspot].
> #[allow(clippy::enum_variant_names)]
> ```

Suppressing clippy warnings is not ideal. Lets aim to address this instead. Could either rename the enum/variants themselves, make a generic error and parameterise the type in the message, or create another layer where there is a single missing option error that take its own option enum with domain, token variants.
___
*[`src/objects.rs` line 15 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQzR3iEQCWxruIw8tE:-NPQzR3iEQCWxruIw8tF:bckoors) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/objects.rs#L15)):*
> ```XML
> }
> 
> impl ToString for ObjectType {
> ```

NIT: Theres a crate that does this via macros called `strum` it means you wouldn't have to implement `to_string` yourself every time a new enum is added.
___
*[`src/objects.rs` line 51 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQzoen0SYIiJkhoivh:-NPQzoen0SYIiJkhoivi:b-7zne83) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/objects.rs#L51)):*
> ```XML
>     /// Deals represent revenue opportunities with a contact or company. They’re tracked through pipeline stages, resulting in the deal being won or lost.
>     pub deals: ApiCollection<ObjectType>,
>     pub line_items: ApiCollection<ObjectType>,
> ```

Missed a doc for this one?
___
*[`src/api_configs/types.rs` line 24 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPpZMQgC_m3gvMTfoEr:-NPpZMQgC_m3gvMTfoEs:b-ltzt6w) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/types.rs#L24)):*
> ```XML
>         self.name().to_path()
>     }
> ```

Doc comment missing

**Review by mterring — COMMENTED** [review]
> Reviewed 24 of 28 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: 28 of 29 files reviewed, 8 unresolved discussions (waiting on @robmarto and @tonisefton)

___
*[`src/api_configs/batch.rs` line 12 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtVoFiAevt-9ODZ-Z3:-NPtVoFiAevt-9ODZ-Z4:b6q9mxo) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/batch.rs#L12)):*
> ```XML
> /// A wrapper type for batch inputs.
> #[derive(Serialize, Debug)]
> pub struct BatchInputs<I> {
> ```

As far as I can see the `Batch*Input`  types are only used internally by this module, so shouldn't be `pub`
___
*[`src/api_configs/mod.rs` line 64 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtc4DZ2RiNzJBy_D2d:-NPtc4DZ2RiNzJBy_D2e:b-2tgqsd) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/mod.rs#L64)):*
> ```XML
>     }
> 
>     /// Read a page of deals. Control what is returned via the properties query param.
> ```

Is this a method for helping write specific object APIs or is it for end user use?



_Suggestion:_
```XML
objects
```
___
*[`src/engagements/mod.rs` line 26 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtefW12L_zWBnViGxd:-NPtefW12L_zWBnViGxe:b-mhactl) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/engagements/mod.rs#L26)):*
> ```XML
>     fn to_path(&self) -> String {
>         match self {
>             EngagementType::Notes => "Notes".to_string().to_lowercase(),
> ```

Given it's a constant, why not:



_Suggestion:_
```XML
"notes".to_string()
```

**Review by mterring — COMMENTED** [review]
> Reviewed 1 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: all files reviewed, 8 unresolved discussions (waiting on @tonisefton)

**Review by robmarto — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: all files reviewed, 9 unresolved discussions (waiting on @tonisefton)

___
*[`src/api_configs/types.rs` line 222 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPuAm49BlFcAVQ4Otv_:-NPuAm49BlFcAVQ4Otva:b-8so8id) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/types.rs#L222)):*
> ```XML
>         AssociationType {
>             id: match self {
>                 KnownBuiltInAssociations::NoteToContact => "202".to_string(),
> ```

As discussed, curious as to what these numbers are and if they are impl sepcific?

**Review by tonisefton — COMMENTED** [review]
As discussed, we are going to bite the bullet with these breaking changes, with the aim to continue adding more objects and entitlements in the lead up to 1.0 and hold additional breaking changes for the 1.0 release.

> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4#-:-NPyIeCa10tHfODZXDfn:b-dsucus)* status: all files reviewed, 9 unresolved discussions (waiting on @robmarto)

___
*[`src/builder.rs` line 36 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQs9Si1aeLLSW-5vsK:-NPyIwBXETmrGvSv42og:b-7zaal2) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/builder.rs#L36)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

Why are these Optional if we are returning an error when they are None?
</blockquote></details>

As discussed, let's review in the eventual 1.0 release as changes to the builder will be breaking changes. 
Also potential to replace this code with a constructor or buildstructor crate
___
*[`src/builder.rs` line 77 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQsjuP-MDJTUTKQK9r:-NPyJDuQAmdKLB36lF_y:bnkndvn) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/builder.rs#L77)):*
> As discussed, let's review in the eventual 1.0 release
___
*[`src/api_configs/types.rs` line 222 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPuAm49BlFcAVQ4Otv_:-NPycwBh4Qe1_rckMisD:b-v3bax) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/types.rs#L222)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

As discussed, curious as to what these numbers are and if they are impl sepcific?
</blockquote></details>

I had a bit of a dabble this morning, and pretty confident that these are generic ids

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: all files reviewed, 8 unresolved discussions (waiting on @mterring and @robmarto)

___
*[`src/objects.rs` line 15 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQzR3iEQCWxruIw8tE:-NPyrTfkBu1U7q0_oA8B:b-742z17) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/objects.rs#L15)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

NIT: Theres a crate that does this via macros called `strum` it means you wouldn't have to implement `to_string` yourself every time a new enum is added.
</blockquote></details>

was meaning to update this, good catch 
___
*[`src/objects.rs` line 51 at r2](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPQzoen0SYIiJkhoivh:-NPyrnUb5D92idcvWvkE:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/681be709238a28818a6687b847cd4c0716e50fb0/src/objects.rs#L51)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

Missed a doc for this one?
</blockquote></details>

Done.
___
*[`src/api_configs/mod.rs` line 64 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtc4DZ2RiNzJBy_D2d:-NPys4aj5B0rMqY_hjFy:b-kg28h) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/mod.rs#L64)):*
<details><summary><i>Previously, mterring (Michael Terrington) wrote…</i></summary><blockquote>

Is this a method for helping write specific object APIs or is it for end user use?
</blockquote></details>

Good catch, fixed. As for your comment, the first, though Hubspot is so customizable there likely is a use case for someone to want to implement these APIs for their own custom objects
___
*[`src/api_configs/types.rs` line 24 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPpZMQgC_m3gvMTfoEr:-NPysapG3MIdiN6X2Lui:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/types.rs#L24)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

Doc comment missing
</blockquote></details>

Done.
___
*[`src/engagements/mod.rs` line 26 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtefW12L_zWBnViGxd:-NPysxpB6VpPtUTHB0mG:b-p6og0m) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/engagements/mod.rs#L26)):*
<details><summary><i>Previously, mterring (Michael Terrington) wrote…</i></summary><blockquote>

Given it's a constant, why not:
</blockquote></details>

using strum instead

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: 23 of 29 files reviewed, 8 unresolved discussions (waiting on @mterring and @robmarto)

___
*[`src/api_configs/batch.rs` line 12 at r4](https://reviewable.io/reviews/WORK180/hubspot-api/4#-NPtVoFiAevt-9ODZ-Z3:-NPyudkv3-W8KPo7Xu9Q:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/65c6db773fb12198958bf33b9184ff3d40fb8ac4/src/api_configs/batch.rs#L12)):*
<details><summary><i>Previously, mterring (Michael Terrington) wrote…</i></summary><blockquote>

As far as I can see the `Batch*Input`  types are only used internally by this module, so shouldn't be `pub`
</blockquote></details>

Done.

**Review by robmarto — APPROVED** [review]
> Reviewed 6 of 28 files at r2, 1 of 1 files at r3, 1 of 3 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/4)* status: all files reviewed, 3 unresolved discussions (waiting on @mterring)

**Pull request merged**
