### PR TITLE
ENG-1078 create hubspot rust crate

### PR DESCRIPTION
**Pull request by tonisefton**
This change is [Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)

### CODE REVIEW

**Review by i-mann — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r1, 6 of 6 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 16 of 19 files reviewed, 13 unresolved discussions (waiting on @robmarto and @tonisefton)

___
*[`README.md` line 2 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMWyiPF0HSNl5KEAmec:-NMWyiPF0HSNl5KEAmed:b-jez9wy) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L2)):*
> ```Markdown
> # Hubspot API Rust Library
> The unofficial Hubspot API Rust Library provides convenient access to the Hubspot CRM API from applications written in the Rust language.
> ```

nit: *This
___
*[`README.md` line 5 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMWylUQ4f8HcWZrz96R:-NMWylUQ4f8HcWZrz96S:bhrcbb) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L5)):*
> ```Markdown
> 
> ## Installation
> To install the Hubspot API from crates.io. Add the following line to your `Cargo.toml`
> ```

comma between sentences?
___
*[`README.md` line 27 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-35V3VVn4MT0oQVX:-NMX-35W9y7Mxfku6FTY:b764ewr) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L27)):*
> ```Markdown
> 
> main.rs
> ```
> ```

if you add `rust` after the 3 backticks, it will render with rust syntax :smile: 
___
*[`README.md` line 38 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-Bji7HSq18Pu-AxW:-NMX-Bji7HSq18Pu-AxX:b-o8hnh1) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L38)):*
> ```Markdown
> 
> ### Usage
> Below is an example of how to read a deal by id.
> ```

`ID` rather than `id` in sentences
___
*[`README.md` line 42 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-GI2B5hul93W6MDB:-NMX-GI2B5hul93W6MDC:bb7o50p) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L42)):*
> ```Markdown
> example.rs
> 
> ```
> ```

rust
___
*[`src/builder.rs` line 20 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-YvZ6WKA_GTbQV7T:-NMX-YvZ6WKA_GTbQV7U:bopyfs0) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L20)):*
> ```XML
> 
> impl HubspotBuilder {
>     /// Get instance of hubspot api builder.
> ```

Perhaps 
`Create an instance of the HubSpot API builder.`
___
*[`src/builder.rs` line 25 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-dvn6mJXesP5hH8b:-NMX-dvn6mJXesP5hH8c:bz7111h) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L25)):*
> ```XML
>     }
> 
>     /// Get instance of hubspot api.
> ```

Perhaps
`Build the Hubspot API (entity?)`
___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMX05oT1tRJRc1PO-Zv:bmo24qc) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
> ```XML
>     token: String,
>     domain: String,
>     pub portal_id: String,
> ```

possibly want to do basic doc on all public fields
___
*[`src/engagements/notes/mod.rs` line 13 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0F3E2O8TUASVU73H:-NMX0F3F68ZZaBDHgYHR:b-h7dwkp) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/engagements/notes/mod.rs#L13)):*
> ```XML
> 
> /// You can log notes on CRM objects to add information to the record timeline or associate an attachment with an object.
> /// For example, if you need to keep track of an offline conversation you had with a contact, you can add a note to their contact record with details and documents related to the conversation.
> ```

nit: newline to keep under 120 chars?
___
*[`src/engagements/notes/note.rs` line 21 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0Ku88P-ymyg7gLAy:-NMX0Ku88P-ymyg7gLAz:b-fsxn7b) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/engagements/notes/note.rs#L21)):*
> ```XML
>     #[serde(rename = "hs_note_body")]
>     pub body: String,
>     /// Required. This field marks the note's time of creation and
> ```

Is it obvious that it's required because it's not an `Option`?
___
*[`src/objects/mod.rs` line 32 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0WKF0piC1Fwn6_he:-NMX0WKF0piC1Fwn6_hf:b19rpy6) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/mod.rs#L32)):*
> ```XML
> /// Depending on your HubSpot subscription, there are additional objects, such as products and custom objects.
> ///
> ///Records are individual instances of an object (e.g., John Smith is a contact). For each record, you can store information in properties, track interactions, and create reports. You can also make associations between records to understand the relationships between them
> ```

nit: whitespace at start
___
*[`src/objects/mod.rs` line 39 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0ab20rdcCx7-NdRC:-NMX0ab20rdcCx7-NdRD:by6fkfu) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/mod.rs#L39)):*
> ```XML
>     /// Companies store information about an individual business or organization.
>     pub companies: CompaniesManager,
>     /// Deals represent revenue opportunities with a contact or company. They’re tracked through pipeline stages, resulting in the deal being won or lost.
> ```

nit: newline
___
*[`src/objects/deals/mod.rs` line 15 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0kkh8DYlsY6joJhH:-NMX0kki0YP_CNDG-mdL:b-v3w9ic) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/deals/mod.rs#L15)):*
> ```XML
> mod deal;
> /// In HubSpot, deals represent transactions with contacts or companies.
> /// Deals are tracked through your sales process in pipeline stages until they're won or lost.
> ```

are these statuses embedded in the code, or are these example states, that can have representative statuses in a hubspot process?

**Review by robmarto — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 16 of 19 files reviewed, 15 unresolved discussions (waiting on @i-mann and @tonisefton)

___
*[`Cargo.toml` line 19 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMaezOs6pwd-8BHKBlB:-NMaezOs6pwd-8BHKBlC:bmbduny) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/Cargo.toml#L19)):*
> ```TOML
> serde = { version = "1.0", features = ["derive"] }
> serde-aux = "4.1.2"
> reqwest = {version = "0.11.13", default-features = false, features = ["json", "rustls-tls"] }
> ```

NIT: If this is going to be a public crate, we shouldnt be enforcing reqwest to use rustls-tls. Ideally it should be a feature of this crate to choose. Maybe it can be left until someone requests this.
___
*[`README.md` line 73 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMai-HY0BRIgmLHZf9p:-NMai-HY0BRIgmLHZf9q:bb7phvt) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L73)):*
> ```Markdown
> 
> ## Contributions
> At this stage we are not configured to accept contribtuions, please check back later. In the meantime please open an issue on github, and we will prioritise accordingly.
> ```

typo



_Code quote:_
```Markdown
contribtuions
```

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 12 of 19 files reviewed, 9 unresolved discussions (waiting on @i-mann and @robmarto)

___
*[`Cargo.toml` line 19 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMaezOs6pwd-8BHKBlB:-NMaq16UBezvLd7F8Ygm:b-pkv9s2) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/Cargo.toml#L19)):*
<details><summary><i>Previously, robmarto (Rob Martin) wrote…</i></summary><blockquote>

NIT: If this is going to be a public crate, we shouldnt be enforcing reqwest to use rustls-tls. Ideally it should be a feature of this crate to choose. Maybe it can be left until someone requests this.
</blockquote></details>

I haven't delved much into crate features yet, so voting to leave for now :sweat_smile:  but completely agree
___
*[`README.md` line 5 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMWylUQ4f8HcWZrz96R:-NMaqGMA1giWXBFNzEb4:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L5)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

comma between sentences?
</blockquote></details>

Done.
___
*[`README.md` line 27 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-35V3VVn4MT0oQVX:-NMaqHCt1sOYEqPzN_iN:b-j1we20) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L27)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

if you add `rust` after the 3 backticks, it will render with rust syntax :smile: 
</blockquote></details>

:raised_hands: 
___
*[`README.md` line 38 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-Bji7HSq18Pu-AxW:-NMaqJuHDOS76xFNzFUT:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L38)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

`ID` rather than `id` in sentences
</blockquote></details>

Done.
___
*[`README.md` line 42 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-GI2B5hul93W6MDB:-NMaqKe17TCAPjasbnNb:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/README.md#L42)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

rust
</blockquote></details>

Done.
___
*[`src/builder.rs` line 20 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-YvZ6WKA_GTbQV7T:-NMaqM-nBNYdf1I6S34W:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L20)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Perhaps 
`Create an instance of the HubSpot API builder.`
</blockquote></details>

Done.
___
*[`src/builder.rs` line 25 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-dvn6mJXesP5hH8b:-NMaqMMcAoX1eUyAgCP7:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L25)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Perhaps
`Build the Hubspot API (entity?)`
</blockquote></details>

Done.
___
*[`src/objects/deals/mod.rs` line 15 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0kkh8DYlsY6joJhH:-NMaqdb5CaWVLJvNSKRc:b-q3ewob) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/deals/mod.rs#L15)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

are these statuses embedded in the code, or are these example states, that can have representative statuses in a hubspot process?
</blockquote></details>

These are example states that can be representative statuses in a hubspot process, we don't have pipelines included in the current crate yet so perhaps once they come in but hubspot is so customizable that it'll likely remain representative

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 12 of 19 files reviewed, 9 unresolved discussions (waiting on @i-mann and @robmarto)

___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMarA1XAAUuirlpP7mJ:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

possibly want to do basic doc on all public fields
</blockquote></details>

Done.
___
*[`src/engagements/notes/note.rs` line 21 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0Ku88P-ymyg7gLAy:-NMarBtB3CDLW9Wp1Yo2:b2nhswy) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/engagements/notes/note.rs#L21)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Is it obvious that it's required because it's not an `Option`?
</blockquote></details>

Yes

**Review by i-mann — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 5 files at r3, 4 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: all files reviewed, 3 unresolved discussions (waiting on @tonisefton)

___
*[`src/builder.rs` line 25 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-dvn6mJXesP5hH8b:-NMbT9O00CJ0RZ-aUOvg:bv2urr9) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L25)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh - the question mark was because I'm unsure of the terminology of the object here - is it called an entity?
___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMbTI6HCOoq7Mdsdywe:b-dd2flk) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Use ID in text :sweat_smile: 
___
*[`src/objects/deals/mod.rs` line 15 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0kkh8DYlsY6joJhH:-NMbTVviEFhZItYas-ou:b-khdrgc) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/deals/mod.rs#L15)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

These are example states that can be representative statuses in a hubspot process, we don't have pipelines included in the current crate yet so perhaps once they come in but hubspot is so customizable that it'll likely remain representative
</blockquote></details>

Ok - in that case I would make it clear that these are example statuses, e.g.



_Code snippet:_
```XML
/// Deals are tracked through your sales process in pipeline stages until they're (say) won or lost.
```

**Review by robmarto — COMMENTED** [review]
all good from me

> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1#-:-NMbYfU28wBay1XTrwVz:bndge4v)* status: all files reviewed, 3 unresolved discussions (waiting on @tonisefton)

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 17 of 19 files reviewed, 3 unresolved discussions (waiting on @i-mann)

___
*[`src/builder.rs` line 25 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX-dvn6mJXesP5hH8b:-NMbaIgu6TXK2BXEzHt4:b-6jqpat) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/builder.rs#L25)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Oh - the question mark was because I'm unsure of the terminology of the object here - is it called an entity?
</blockquote></details>

Nah library
___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMbaKrhBbVljumc-Ixt:bd11a11) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Use ID in text :sweat_smile: 
</blockquote></details>

Oh sorry, I used find and replace which is actually really hard with id :sweat_smile: 
___
*[`src/objects/deals/mod.rs` line 15 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0kkh8DYlsY6joJhH:-NMbaQlz9BWCeEF6U7r_:bckntnf) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/deals/mod.rs#L15)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Ok - in that case I would make it clear that these are example statuses, e.g.
</blockquote></details>

I just removed this line to be more concise.

**Review by i-mann — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: all files reviewed, 1 unresolved discussion (waiting on @tonisefton)

___
*[`src/objects/deals/mod.rs` line 15 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX0kkh8DYlsY6joJhH:-NMk50w8AI1sckuqdKFt:b1y9g65) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/objects/deals/mod.rs#L15)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

I just removed this line to be more concise. 
</blockquote></details>

Yeah. The thing to avoid was being opinionated about how other organisation's processes worked.

**Review by i-mann — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: all files reviewed, 1 unresolved discussion (waiting on @tonisefton)

___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMk5E8f14VcJprIXxaK:b-oftua5) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
<details><summary><i>Previously, tonisefton (Toni Sefton) wrote…</i></summary><blockquote>

Oh sorry, I used find and replace which is actually really hard with id :sweat_smile: 
</blockquote></details>

Two lines above, in the comment?

**Review by tonisefton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: 15 of 19 files reviewed, 1 unresolved discussion (waiting on @i-mann)

___
*[`src/client/mod.rs` line 14 at r3](https://reviewable.io/reviews/WORK180/hubspot-api/1#-NMX05oT1tRJRc1PO-Zu:-NMkZMRxE-4EMjEVDW0b:b-896fix) ([raw file](https://github.com/WORK180/hubspot-api/blob/dbbbfad9ccadf1656bf006a0c112844611c329da/src/client/mod.rs#L14)):*
<details><summary><i>Previously, i-mann (Isaac Mann) wrote…</i></summary><blockquote>

Two lines above, in the comment?
</blockquote></details>

Done.

**Review by i-mann — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/WORK180/hubspot-api/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tonisefton)

**Pull request merged**
